### ISSUE TITLE
그리드 스타일

### ISSUE THREAD

**Issue by jinhoyim** [goexpert/Aware-1920#4]

**Comment by uniorion** [comment]
저한테 배정된거 같은데, 나예님이 그리드 다 적용하신거 같아요
일단 닫아 볼게요ㅎ

**Comment by nayea** [comment]
잘..올라간건가요..?

**Comment by jinhoyim** [comment]
@uniorion  assignees 설정하는거 알려줬어요. ㅎㅎ
@nayea scss 같은 css?

**Comment by nayea** [comment]
ㅋㅋ 이제 style을 sass로 ㅋㅋ

**Comment by jinhoyim** [comment]
@nayea 그럼 다시 리오픈 ㅋㅋ
